global:
  resolve_timeout: 5m

# Route configuration
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h
  receiver: discord

# Receivers configuration
receivers:
- name: discord
  discord_configs:
  - webhook_url: ${DISCORD_WEBHOOK_URL}
    send_resolved: true