services:
  aleo-oracle-notarization-backend:
    image: ${APP}:latest
    container_name: aleo-oracle-notarization-backend
    build: 
      context: ../..
      dockerfile: deployment/docker/Dockerfile
      secrets:
        - gramine-private-key
      args:
        APP: ${APP}
    platform: linux/amd64
    ports:
      - 8000:8000
      - 8001:8001
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
      
secrets:
  gramine-private-key:
    file: ${ENCLAVE_SIGNING_KEY_FILE}